yatube/about/urls.py
# файл about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
# posts/urls.py Версия от 8 февраля. Устранение замечаний Алексея Фролова
from django.urls import path
from . import views

app_name = 'posts'
# app_name = 'about'


urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
]

yatube/users/urls.py
# users/urls.py

# Импортируем из приложения django.contrib.auth нужный view-класс
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordChangeDoneView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView
from django.contrib.auth.views import PasswordResetCompleteView
from django.contrib.auth.views import PasswordResetConfirmView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('password_change/', PasswordChangeView.as_view(
         template_name='users/password_change_form.html'),
         name='password_change_form'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
         template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(
         template_name='users/password_reset_form.html'),
         name='password_reset_form'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
         template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
         template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
         template_name='users/password_reset_complete.html'),
         name='password_reset_complete'), ]

yatube/yatube/urls.py
# yatube/urls.py Версия от 3 февраля. Финиш
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/about/models.py
from django.db import models

# Create your models here.

yatube/posts/models.py
# моделс. Версия от 8 февраля. Устранение замечаний Алексея Фролова
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )

    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='group')

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        # выводим текст поста
        return self.text

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


#  создадим собственный класс для формы регистрации
#  сделаем его наследником предустановленного класса UserCreationForm
class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        # укажем модель, с которой связана создаваемая форма
        model = User
        # укажем, какие поля должны быть видны в форме и в каком порядке
        fields = ('first_name', 'last_name', 'username', 'email')


# class PasswordChangeForm(UserCreationForm):
#    class Meta(UserCreationForm.Meta):
#        model = User
#        fields = ('old_password', 'new_password1', 'new_password2')

yatube/about/views.py
# about/views.py
from django.views.generic.base import TemplateView
# Импортировать TemplateView


# Описать класс AboutAuthorView для страницы about/author
class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


# Описать класс AboutTechView для страницы about/tech
class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
# posts/views.py Версия от 8 февраля. Устранение замечаний Алексея Фролова
from django.shortcuts import render, get_object_or_404
from .models import Post, Group
from yatube.settings import POSTS_PER_PAGE
from django.core.paginator import Paginator
from django.contrib.auth import get_user_model

User = get_user_model()


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.group.all()
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'group': group,
        'posts': posts
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    # Здесь код запроса к модели и создание словаря контекста
    title = f'Профайл пользователя {username}'
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('group', 'author')
    page_number = request.GET.get('page')
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_obj = paginator.get_page(page_number)
    post_count = Post.objects.count()
    context = {
        'post_count': post_count,
        'page_obj': page_obj,
        'username': author,
        'posts': posts,
        'title': title,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    # Здесь код запроса к модели и создание словаря контекста
    post = get_object_or_404(Post, pk=post_id)
    post_count = Post.objects.count()
    title = f' Пост {post.text[:30]}'
    context = {
        'post': post,
        'post_count': post_count,
        'title': title,
    }
    return render(request, 'posts/post_detail.html', context)

yatube/users/views.py
# users/views.py
# Импортируем CreateView, чтобы создать ему наследника
from django.views.generic import CreateView

# Функция reverse_lazy позволяет получить URL по параметрам функции path()
# Берём, тоже пригодится
from django.urls import reverse_lazy

# Импортируем класс формы, чтобы сослаться на неё во view-классе
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    # После успешной регистрации перенаправляем пользователя на главную.
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'
# Create your views here.


# class PasswordChenge(CreateView):
#    form_class = PasswordChangeForm
#    success_url = reverse_lazy('/auth/password_change/')
#    template_name = 'users/password_change_form.html'

yatube/templates/about/author.html
<!-- templates/about/author.html -->
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я Ефремов Олег</h1>
<p>
  Родился, Учился, работал и продолжаю Учиться.
</p>
{% endblock %}

yatube/templates/about/tech.html
<!-- templates/about/tech.html -->
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот что я умею</h1>
  {% comment %}
    Боковой блок со списком технологий 
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
  {% endcomment %}
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  {% comment %}
    Статья  
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  {% endcomment %}
  <article class="col-12 col-md-9">
    <p>Текст страницы "Технологии"</p>
  </article>
</div>
{% endblock %}

yatube/templates/base.html
<!--posts/base.html Версия от 8 февраля. Устранение замечаний Алексея Фролова-->
{% load static %}
<html lang="ru">
  <head>
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}Последние обновления на сайте{% endblock %}</title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
        {% for post in page_obj %}
          Контент не подвезли :(
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
      {% endblock %}
    </main>
    <footer>
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<html lang="ru">
  <footer class="border-top text-center py-3">
    <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
  </footer>

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      {# Добавлено в спринте #}

      {% comment %}
      Меню - список пунктов со стандартными классами Bootsrap.
      Класс nav-pills нужен для выделения активных пунктов 
      {% endcomment %}
      <ul class="nav nav-pills">
        {% with request.resolver_match.view_name as view_name %} 
        <li class="nav-item">
          <a class="nav-link 
            {% if view_name  == 'about:author' %}
              active
            {% endif %}"
            href="{% url 'about:author' %}"
          >
            Об авторе
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link
            {% if view_name  == 'about:tech' %}
              active
            {% endif %}"
            href="{% url 'about:tech' %}"
          >
            Технологии
          </a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link
            {% if view_name  == 'about:tech' %}
              active
            {% endif %}"
            href="{% url 'about:tech' %}"
          >
            Новая запись
          </a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light
            {% if view_name  == 'users:password_change' %}
              active
            {% endif %}"
            href="{% url 'users:password_change_form' %}"
          >
            Изменить пароль
          </a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light
          {% if view_name  == 'users:logout' %}
              active
            {% endif %}"
            href="{% url 'users:logout' %}" 
          >
            Выйти
          </a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light
            {% if view_name  == 'users:login' %}
              active
            {% endif %}"
            href="{% url 'users:login' %}" 
          >
            Войти
          </a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light
            {% if view_name  == 'users:signup' %}
              active
            {% endif %}"
            href="{% url 'users:signup' %}" 
          >
            Регистрация
          </a>
        </li>
        {% endif %}
        {% endwith %}  
      </ul>
      {# Конец добавленого в спринте #}
    </div>
  </nav>      
</header>

yatube/templates/posts/group_list.html
<!--posts/group_liist.html Версия от 8 февраля. Устранение замечаний Алексея Фролова-->
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="ru">
<title>{% block title %} Страница групп сообществ{% endblock %}</title>
{% block content %}
  <div class="container py-5">
    <h1>Группа сообщества</h1>
    <p>{{ group.title }}</p>
    <article>
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>
        {% if not forloop.last %} <hr> {% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/includes/paginator.html
{# templates/posts/includes/paginator.html #}

{% comment %}
Отрисовываем навигацию паджинатора только если
все посты не помещаются на первую страницу
{% endcomment %}
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
<!--posts/base.html Версия от 8 февраля. Устранение замечаний Алексея Фролова-->
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Последние новости на сайте</h1>
    {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p> {{post.text}} </p>
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
      {% if not forloop.last %} <hr> {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
  Подробная информация поста {{ author }}
{% endblock %} 
{% block header %}Детали поста{% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}  
        <li class="list-group-item">
          Группа: {{group.title}}
          <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы
          </a>
        </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: {{post_count}}
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>
        {{post.text}}
      </p>
    </article>
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  Профайл пользователя {{ author }}
{% endblock %} 
{% block header %}Профайл пользователя{% endblock %}
{% block content %}
  <div class="container py-5">        
    <h1>Все посты пользователя {{author}} </h1>
      <h3>Всего постов: {{post_count}}</h3>   
        <article>
        {% for post in page_obj %}  
          <ul>
            <li>
              Автор:{{ post.author.get_full_name }}
              <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>
            {{post.text}}
          </p>
          <ul>
            <li>
              <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
            </li>
            <li>
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            </li>
          </ul>             
        <hr>
        {% if not forloop.last %} <hr> {% endif %}
        {% endfor %}
      </article> 
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/users/logged_out.html
{# Это код файла templates/users/logged_out.html #}

{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/login.html
# templates/users/login.html

{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change_done.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <title>Пароль изменён</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="../posts/index.html">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Пароль изменён
              </div>
              <div class="card-body"> 
                <p>Пароль изменён успешно</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>

yatube/templates/users/password_change_form.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <title>Изменение пароля</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Изменить пароль
              </div>
              <div class="card-body">
                <form method="post" action="../users/password_change_form.html">
                  
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  <div class="form-group row my-3 p-3">
                    <label for="id_old_password">
                      Старый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                      <small id="id_new_password1-help" class="form-text text-muted">
                        <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                      </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Изменить пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>

yatube/templates/users/signup.html
<!-- templates/users/signup.html -->
{% extends "base.html" %}

<title> {% block title %}Зарегистрироваться{% endblock %} </title>
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}